#!/usr/bin/env bash

# core variables
export EDITOR="subl -w"

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export HISTDUP="prev"
export HISTSIZE=20000
export HISTFILESIZE=10000
export HISTIGNORE="ls:* --help"

export LS_COLORS='ex=00:su=00:sg=00:ca=00:'

export PROMPT_COMMAND="history -a;$PROMPT_COMMAND"

export FLASK_ENV=development

alias ls='ls -FG'

function update_terminal_cwd() {
    # Identify the directory using a "file:" scheme URL,
    # including the host name to disambiguate local vs.
    # remote connections. Percent-escape spaces.
    local SEARCH=' '
    local REPLACE='%20'
    local PWD_URL="file://$HOSTNAME${PWD//$SEARCH/$REPLACE}"
    printf '\e]7;%s\a' "$PWD_URL"
}

# Always lists working directory while cd
function __cd()
{
    cd -L "$@"
    if $([[ $(ls | wc -l) -le 20 ]]); then
        ls
    fi
}
alias cd="__cd"

# Print both symbolic and physical working directory
function __pwd()
{
    pwd
    if $([[ "$(\pwd)" != "$(\pwd -P)" ]]); then
        pwd -P
    fi
}
alias pwd="__pwd"

# Uses sublime text in background for man pages
function __man()
{
    man "$@" | col -b | subl -w &
}
alias man="__man"

# Adds overused flags on common git functions
function __git()
{
    if $([[ $@ == "log" ]]); then
        git log --oneline --graph
    elif $([[ $@ == "push" ]]); then
        git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD)
    elif $([[ $@ == "branch-clean" ]]); then
        git branch | grep -v "master" | xargs git branch -D
        git fetch --all --prune
    else
        git "$@"
    fi
}
alias git="__git"
