#!/usr/bin/env bash

# Setup PATH
prepends=(
    "venv/bin"
    "usr/local/cuda-10.0/bin"
    "$HOME/.local/bin"
)

appends=(
    "$HOME/.phacility/arcanist/bin"
)

for (( i=${#prepends[@]}-1; i>=0; i-- )); do
    PATH="${prepends[i]}:$PATH"
done

for (( i=0; i<${#appends[@]}; i++ )); do
    PATH="$PATH:${appends[i]}"
done

export PATH

unset prepends
unset appends

# Core variables
export LD_LIBRARY_PATH="/usr/local/cuda-10.0/lib64:$LD_LIBRARY_PATH"

export EDITOR="subl -w"

# Use "open" to open
alias open="xdg-open"

# Additional ls alias
alias ll='ls -alF --block-size=M'

# Always lists working directory while cd
function __cd()
{
    cd -L "$@"
    if $([[ $(ls | wc -l) -le 20 ]]); then
        ls
    fi
}
alias cd="__cd"

# Print both symbolic and physical working directory
function __pwd()
{
    pwd
    if $([[ "$(\pwd)" != "$(\pwd -P)" ]]); then
        pwd -P
    fi
}
alias pwd="__pwd"

# Uses sublime text in background for man pages
function __man()
{
    if [ -x /usr/bin/vipe ]; then
        man "$@" | vipe > /dev/null &
    else
        man "$@"
    fi
}
alias man="__man"

# Adds overused flags on common git functions
function __git()
{
    if $([[ $@ == "log" ]]); then
        git log --oneline --graph
    else
        git "$@"
    fi
}
alias git="__git"
